# Aula 9 - Preparatório para a aula de Físicos, Engenharia e Matemática - Parte 1 : NumPy

* `NumPy` é um pacote para a linguagem Python que suporta arrays e
matrizes multidimensionais, possuindo uma larga coleção de funções
matemáticas para trabalhar com estas estruturas.

* `NumPy` foi criado em 2005 por `Travis Oliphant`

* É um projeto comunitário, multiplataforma, de código livre.

`NumPy` é utilizado em... qualquer tarefa matemática

* `NumPy` é bastante útil para executar várias tarefas matemáticas como
integração numérica, diferenciação, interpolação, extrapolação e
muitas outras.

* O `NumPy` possui também funções incorporadas para álgebra linear,
transformadas de fourrier e geração de números aleatórios.

* Quando usada em conjunto com `SciPy` e `Matplotlib` , pode substituir
programas como o Matlab para o tratamento de tarefas matemáticas.

<p align="center">
  <img width="700" height="326" src= "https://miro.medium.com/max/1400/1*itm7jgcg83noLZPzol6LHQ.png">
</p>

### `NumPy` é utilizado por... Processamento de Imagem e Computação Gráfica
* Imagens no computador são representadas como Arrays Multidimensionais de
números.

* `NumPy` torna se a escolha mais natural para o mesmo.

* O `NumPy` , na verdade, fornece algumas excelentes funções de biblioteca para
rápida manipulação de imagens.

* Alguns exemplos são o espelhamento de uma imagem, a rotação de uma
imagem por um determinado ângulo etc.

### NumPy é utilizado por... Machine Learning
* Ao escrever algoritmos de Machine Learning, supõe se que se realize vários
cálculos numéricos em Array .
    * Por exemplo, multiplicação de Arrays , transposição, adição, etc.
* O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de
escrita de código) e rápidos (em termos de velocidade).
* Os Arrays NumPy são usados para armazenar os dados de treinamento, bem
como os parâmetros dos modelos de ML. 

### Por que usar `NumPy`
* Em Python usamos listas para tratar vetores e matrizes, mas elas são lentas
para processar.
* O `NumPy` fornece um objeto array que é até 50x mais rápido que o Python tradicional.
    * O objeto array em `NumPy` fornece funções de suporte que tornam o trabalho com
vetores e matrizes muito fácil.
* Os arrays são muito frequentemente usados em ciência de dados, onde
velocidade e recursos são muito importantes.    
* Os arrays `NumPy` são armazenados em um lugar contínuo na memória ao
contrário das listas, para que os processos possam manipulá los de forma muito
eficiente.
    * Esse comportamento é chamado de localidade de referência em ciência da
computação.
* Esta é a principal razão pela qual o `NumPy` é mais rápido do que as listas.
* Também é otimizado para trabalhar com as mais recentes arquiteturas de CPU.

__Para utilizar o Numpy é necessario instalá-lo , usando o comando:__
```python
    pip install numpy   # caso utilize o pip
    conda install numpy # caso utilize o conda
    sudo apt-get install python-numpy # Linux Terminal
```

### Usando o NumPy
Para utilizar a biblioteca NumPy em um programa, é necessário importa-la:
```python
    import numpy as np
```

### Criando arrays em NumPy

* Array diferem-se de lista pois o conteudo é tratado com um vetor!


$ a =\begin{bmatrix}
x\\ 
y\\ 
\end{bmatrix}$ 

Podemos criar um objeto ndarray usando a função array:

In [2]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


Para criar um array , podemos passar uma lista, tupla ou qualquer objeto semelhante a matriz no método array () e ele será convertido em um objeto do tipo ndarray

In [3]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


Criar um ndarray a partir de sequências aninhadas irregulares.

In [4]:
arr = np.array([[1,2],[3,4,5]])
print(arr)

[list([1, 2]) list([3, 4, 5])]


C:\Users\thoma\AppData\Local\Temp/ipykernel_6892/1979004199.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2],[3,4,5]])


### Dimensão em arrays
0-D: Representa um número escalar


In [5]:
arr = np.array(1)
print(arr)

1


1-D: Representa um Vetor


In [6]:
arr = np.array([1,2])
print(arr)

[1 2]


2-D:
* Um array que tem arrays 1D como seus elementos é chamado de array 2D.   
* Estes são frequentemente usados para representar matrizes.
* `NumPy` tem um subconjunto inteiro dedicado às operações de matriz.

In [7]:
arr = np.array([[1,2,3],
               [3,4,5],
               [7,8,9]])
print(arr)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


3-D:
* Um array que tem arrays 2D como seus elementos é chamado de array 3D.

* Estes são frequentemente usados para representar um tensor de 3ª ordem.

In [8]:
arr = np.array([[[1,2,3],
                [3,4,5]],
               [[7,8,9],
                [10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]


Dimensões superiores: Tensores


<p align="center">
  <img width="400" height="267" src= "https://miro.medium.com/max/538/1*kHues3bfBOythrXNLosesQ.png">
</p>

### Descobrindo a dimensão de um array
* O NumPy Arrays fornece o atributo `ndim `que retorna um inteiro que
nos diz quantas dimensões o array tem.



In [9]:
a = np.array(12)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


### Índices dos arrays
Elementos dos arrays são acessados iguais as listas.

In [10]:
arr = np.array([1,2,3,4])
print(arr[2])

3


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][2])


6


### Índices negativos
* Igual às listas, os índices negativos indexam os elementos
a partir do final do array

In [12]:
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Ultimo elemento da segunda lista: ",arr[1,-1])

Ultimo elemento da segunda lista:  10


### Fatiamento de arrays
* Fatiar em Python significa pegar elementos de um dado índice até outro dado índice.
* Para fatiar usamos os índices como:
    * [`start` : `end`]
    * Se não definirmos o `start`, se considera iniciado em 0.
    * Se não passarmos o `end`, se fatia até o final da dimensão.
* Também podemos definir o passo, assim:
    * [ `start` : `end` : `step`]

In [13]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:2])
print(arr[:5])
print(arr[4:])
print(arr[1:7:2])

[1 2]
[1 2 3 4 5]
[5 6 7]
[2 4 6]


### Fatiamento de arrays de mais dimensões

In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### Fatiamento de arrays : retirando uma linha ou coluna

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


Capturando um linha:


In [16]:
print(arr[1,:])

[4 5 6]


Capturando uma coluna:

In [17]:
print( arr[:, 1])

[2 5 8]


### Tipos de dados do NumPy
* O NumPy define mais tipos de dados que os existentes em Python:
    * Existem:
        * i - integer
        * b - boolean
        * u - unsigned integer
        * f - float
        * c - complex float
        * m - timedelta
        * M - datetime
        * O - object
        * S - string
        * U - unicode string
        * V - fixed chunk of memory for other type ( void )
* Para descobrir o tipo de dado em NumPy use `dtype()`
        


In [18]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [19]:
arr = np.array([1.0,2.0,3.0])
print(arr.dtype)

float64


In [20]:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


### Criando um array com um tipo de dado definido
* A função array () usada para criar arrays pode ter um argumento
opcional dtype que nos permite definir o tipo de dados esperado
dos elementos de matriz:
```python
    arr = np.array ([ 2, 3, 4], dtype = "s")
```
Foi criado um array de strings com os números.

### Tipos de dados do NumPy
* Os tipos i u f S and U permitem definir o tamanho, em bytes.
* Se define com 2, 4 ou 8 bytes para números
* Para strings , se define a quantidade de caracteres

In [21]:
arr = np.array([1,2,3,4,5], dtype = "S5" )
print(arr.dtype)

|S5


### Copiando um array
* Para copiar um array é necessário utilizar a função `copy()`


In [22]:
arr =  np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42 
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


* Quando não usamos a função `copy ()`, criamos apenas uma
referência para o array original:

In [23]:
arr =  np.array([1,2,3,4,5])
x = arr
arr[0] = 42 
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Shape de um array
* O shape , ou forma , de um array , é dado pelo número de elementos em cada dimensão.
* Os arrays `NumPy` têm um atributo chamado shape que retorna uma
tupla com cada índice tendo o número de elementos correspondentes
em cada dimensão:

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


### Reshaping arrays
* Reshape significa mudar a forma de um array
* Reshaping podemos adicionar ou remover dimensões ou alterar o número de elementos em cada dimensão.
* Muito usado em ciência de dados e ML.
* Utiliza se o método `reshape (newshape)`:
    * `newshape` define a nova forma do array
    * Pode ter qualquer forma, desde que o número de elementos do novo array seja igual ao original.

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(4,2)
new2arr = arr.reshape(2,4)
new3arr = arr.reshape(2,2,2)
print(arr)
print('')
print('****')
print('')
print(newarr)
print('')
print('////')
print('')
print(new2arr)
print('')
print('----')
print('')
print(new3arr)
print('')


[1 2 3 4 5 6 7 8]

****

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

////

[[1 2 3 4]
 [5 6 7 8]]

----

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



### Flattening
* Reduz qualquer array multidimensional à uma
dimensão

In [26]:
new4arr = arr.reshape(-1)
print(new4arr)

[1 2 3 4 5 6 7 8]


### Iterando nos arrays NumPy
* Iterar em um array NumPy é semelhante a iterar em listas.
* Utiliza se um comando de repetição como o `for`:

In [27]:
arr = np.array ([1, 2, 3])
for x in arr:
    print (x)

1
2
3


### Iterando nos arrays NumPy 2D
* Iterar em um array NumPy é semelhante a iterar em listas.

* Utiliza se um comando de repetição como o `for`:

In [28]:
arr = np.array ([[ 2, 3],[4, 5, 6]])
for x in arr:
    print (x)

[2, 3]
[4, 5, 6]


C:\Users\thoma\AppData\Local\Temp/ipykernel_6892/1741564835.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array ([[ 2, 3],[4, 5, 6]])


* Iterar em um array NumPy é semelhante a iterar em listas.

* Utiliza se um comando de repetição como o `for`:
    

In [29]:
arr = np.array ([[1, 2, 3],[4, 5, 6]])
for x in arr:
    for y in x:
        print (y)

1
2
3
4
5
6


### Iterando nos arrays NumPy 3D
* Iterar em um array NumPy é semelhante a iterar em listas.
* Utiliza se um comando de repetição como o `for`:

In [30]:
arr = np.array ([[[1,2],[3,4]],[[5, 6],[7,8]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


### Busca em arrays
* Para pesquisar um array , use o método `where()`:

In [31]:
arr = np.array ([1, 2, 3, 4, 5, 4, 4])
x =  np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


### Ordenando arrays
* Ordenar significa colocar elementos em uma sequência ordenada.

* Sequência ordenada é qualquer sequência que tem uma ordem
correspondente a elementos, como numérico ou alfabético,
ascendente ou descendente.

* O objeto array em NumPy tem uma função chamada `sort()`, que
classificará um array especificado.

In [32]:
arr1 = np.array([3,5,7,4,9,2,8,3,6,1])
arr2 = np.array(['Banana','Cherry','Apple'])
arr3 = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(arr3))

[1 2 3 3 4 5 6 7 8 9]
['Apple' 'Banana' 'Cherry']
[[2 3 4]
 [0 1 5]]


## Funções Básicas

### Realizando operações entre arrays
* O NumPy define diversas operações matemáticas entre martrizes ,
otimizadas para velocidade de processamento.

* Todas as operações básicas são definidas:
    * Soma, subtração, multiplicação e divisão escalar de vetores

    * Multiplicação vetorial

    * Multiplicação de matrizes

    * ...

### Criando matrizes automaticamente

In [33]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.random.rand(3,2)

array([[0.71958395, 0.23487414],
       [0.38456157, 0.03273097],
       [0.78193166, 0.91375718]])

### Soma escalar

In [36]:
data = np.array ([1,2])
print(data)
ones = np.ones (2, dtype=int)
print(ones)

[1 2]
[1 1]


In [37]:
data + ones

array([2, 3])

### Subtração, multiplicação, divisão escalar

In [38]:
data - ones

array([0, 1])

In [39]:
data * ones

array([1, 2])

In [40]:
data / data

array([1., 1.])

### Broadcast, ou multiplicação por um escalar

In [41]:
data = np.array ([1.0,2.0])
data * 1.6

array([1.6, 3.2])

### Soma de matrizes

In [42]:
data = np.array ([[1, 2], [3, 4]])
ones = np.array ([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

### Soma de matrizes de diferentes tamanhos

In [43]:
data = np.array ([[1, 2], [3, 4], [5,6]])
print(data)


[[1 2]
 [3 4]
 [5 6]]


In [44]:
ones_row = np.array ([[1,1]])
print(ones_row)

[[1 1]]


In [45]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

### Multiplicação dos elementos das matrizes

In [46]:
data = np.array ([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [47]:
data2 = np.array ([[5, 6], [7, 8]])
print(data2)

[[5 6]
 [7 8]]


In [48]:
data * data2

array([[ 5, 12],
       [21, 32]])

### Produto escalar
* O produto escalar é uma operação definida entre dois vetores que
fornece um número real (também chamado "escalar") como
resultado.
    * É o produto interno padrão do espaço euclidiano.
* Algebricamente, o produto escalar de dois vetores é formado pela
multiplicação de seus componentes correspondentes e pela soma dos
produtos resultantes.
    * Geometricamente, é o produto das magnitudes euclidianas dos dois
vetores e o cosseno do ângulo entre eles.    

<p , align = "center">
 <img width="400" height="307" src= "https://www.igm.mat.br/igm/igm1/equipe-igm/desc-convertidos/matrizes/produto2_arquivos/image007.jpg">
</p>

### Multiplicação de matriz


<p , align = "center">
 <img width="400" height="223" src= "https://docplayer.com.br/docs-images/39/18825811/images/3-0.png">
</p>

### Produto escalar em NumPy


In [49]:
data = np.array ([1, 2])
data2 = np.array ([3, 4])
x = data.dot(data2)
print(x)

11


In [51]:
data3 = np.array([4,5])
y = data.dot(data3)
print(y)

14


### Multiplicação de matriz em NumPy

In [ ]:
data = np.array ([[1, 2], [3, 4]])
data2 = np.array ([[5, 6], [7, 8]])
x = data.dot(data2)
print(x)

[[19 22]
 [43 50]]


### Produto Vetorial em NumPy
* O produto vetorial é uma operação sobre
dois vetores em um espaço tridimensional e é
denotado por × .
    * Dados dois vetores independentes
linearmente a e b , o produto vetorial a × b é um
vetor perpendicular ao vetor a e ao vetor b e é a
normal do plano contendo os dois vetores.
* Seu resultado difere do produto escalar por ser
também um vetor, ao invés de um escalar.

<p , align = "center">
 <img width="400" height="555" src= "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Cross_product_vector.svg/1200px-Cross_product_vector.svg.png">
</p>

Em NumPy , o produto vetorial, também chamado cross , é escrito como:
`cross()`


* O produto vetorial de a e b R3 é um vetor perpendicular a a e b.
* Se a e b são matrizes de vetores, os vetores são definidos pelo último eixo
de a e b por padrão, e esses eixos podem ter dimensões 2 ou 3.
    * Nos casos em que ambos os vetores de entrada têm dimensão 2, o componente z do cruzamento
produto é devolvido

    * Onde a dimensão de a ou b é 2, o terceiro componente do vetor de entrada é
assumido como sendo zero e o produto vetorial calculado de acordo.

In [ ]:
data = np.array ([1, 2, 3])
data2 = np.array ([4, 5, 6])
y = np.cross (data,data2)
print(y)

[-3  6 -3]


### Produto vetorial em NumPy

In [ ]:
data = np.array ([[1,2,3],[4,5,6],[1,0,0]])
data2 = np.array ([[4,5,6],[4,5,6],[0,1,0]])
y = np.cross(data, data2)
print(y)

[[-3  6 -3]
 [ 0  0  0]
 [ 0  0  1]]


## Finalmentes ...

Matriz transposta

```python
    arr.transpose() ou arr.T
```

In [ ]:
M =[[1,2,3],[4,5,6],[7,8,9]]
print(M)
print("")
M_t = np.array(M).T
print(M_t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Inversão de matriz
* A matriz inversa de uma matriz é tal que se for
multiplicada pela matriz original, resulta em matriz
identidade.
* Usamos a função` numpy.linalg.inv()` para calcular a
inversa de uma matriz.

In [ ]:
x = np.array ([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print("---")
print((np.dot (x,y)))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
---
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### Máximo, mínimo, soma

In [ ]:
data = np.array([1,2,3])
data.max()

3

In [ ]:
data.min()

1

In [ ]:
data.sum()

6

### Máximo, mínimo, soma por linha ou coluna

In [ ]:
data = np.array([[1,2],[3,4],[5,6]])
data.max(axis = 0) #Olhara o maior valor utilizando as colunas como parametro 

array([5, 6])

In [ ]:
data.max(axis = 1)#Olhara o maior valor utilizando as linhas como parametro 

array([2, 4, 6])

Terminamos a Primeira parte, mas ainda ha coisa que irei tratar sobre vetores nas proximas aulas como a representação grafica de soma de vetores.

Antes disso precisamos ver como construir graficos

### Conclusão
* NumPy provém uma maneira simples tratar vetores,
matrizes e dados em geral.
* NumPy resolve quase toda matemática...
* NumPy possui muitas outras funções prontas...


     <[Referencias] (https://numpy.org/doc/stable/reference/routines.html)>